version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: wellness_postgres
    environment:
      POSTGRES_DB: wellness_tracker_db
      POSTGRES_USER: wellness_user
      POSTGRES_PASSWORD: wellness_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U wellness_user -d wellness_tracker_db"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped

volumes:
  postgres_data:
